import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import * as nodeFs from 'node:fs';
import { mkdtempSync, rmSync, readFileSync, readdirSync, existsSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { join, dirname, relative } from 'node:path';
import { planInit } from '../../core/src/scaffold/plan.mjs';
import { renderHandoffMd } from '../../core/src/bundle/render.mjs';
import { renderResumePrompt } from '../../core/src/receive/prompt.mjs';

// ---------------------------------------------------------------------------
// Repo-wide zero-attribution INVARIANT (plan §Attribution guard layer 3: "a
// test-suite invariant scans every rendered output and template for AI-credit
// strings and fails the build"; Acceptance constraint 5; docs/design/core.md
// §invariants: "no AI-credit strings in any rendered output, golden, or
// template").
//
// TARGET MODULE: core/src/scaffold/plan.mjs (sole target — its absence is the
// only reason this file is RED). The scanner + positive control mirror
// tests/unit/receive-prompt.test.mjs verbatim.
//
// FOUR SCAN ARMS, each guarded against a vacuous pass (verifier fold F3 — a
// single harmless preview must NOT be enough to go green):
//   A1. TEMPLATES TREE. The shipped `templates/` directory is walked
//       RECURSIVELY and every file's content is scanned. The plan pins the
//       template set (§Templates "template templates/AGENTS.md.tpl"; repo map
//       "templates/ — scaffolded AGENTS.md / CLAUDE.md / baton.config.json"),
//       so this arm FAILS if templates/ is missing, is empty, or lacks any of
//       the three pinned filenames: AGENTS.md.tpl, CLAUDE.md.tpl,
//       baton.config.json.tpl. (Build order puts the templates commit before
//       scaffold/init, so by the time this file's target module exists the
//       tree must too.)
//   A2. GOLDEN FIXTURES. Every file in tests/helpers/fixtures/golden/ is
//       discovered dynamically (readdir, NOT a hardcoded list — a golden added
//       later is scanned automatically) and scanned; the arm fails if the
//       directory yields no files.
//   A3. LIVE RENDERED OUTPUT. renderHandoffMd + renderResumePrompt over
//       canonical inputs.
//   A4. SCAFFOLD PREVIEWS. planInit(cwd, opts, io) -> Action[] with
//       Action.preview: string (the exact bytes init would write), called over
//       an empty real-fs tmp cwd — the rendered-scaffold arm; at least one
//       preview must be scanned.
// ---------------------------------------------------------------------------

// Mirrors tests/unit/receive-prompt.test.mjs (and render.test.mjs) VERBATIM.
// Deliberately narrow so it never trips on legitimate platform/model identifiers
// ("claude-code", "gpt-5.6-sol") that are real data, not attribution.
const ATTRIBUTION_PATTERNS = [
  /co-authored-by/i,
  /generated with claude/i,
  /generated by claude/i,
  /🤖/,
  /written by (an? )?ai\b/i,
  /authored by (an? )?ai\b/i,
  /powered by claude/i,
];
const scanAttribution = (text) => ATTRIBUTION_PATTERNS.filter((re) => re.test(text)).map((re) => re.source);

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..', '..');
const TEMPLATES_DIR = join(repoRoot, 'templates');
const GOLDEN_DIR = join(repoRoot, 'tests', 'helpers', 'fixtures', 'golden');

/** Recursively collect every file path under `dir` on the real fs. */
function walkFiles(dir) {
  /** @type {string[]} */
  const out = [];
  if (!existsSync(dir)) return out;
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...walkFiles(p));
    else out.push(p);
  }
  return out;
}

const T0 = '2026-07-11T00:00:00.000Z';

function liveBundle() {
  return {
    schema: 'baton/bundle@1',
    bundleId: 'b_inv0000000000',
    generation: 1,
    createdAt: T0,
    updatedAt: T0,
    origin: { platform: 'claude-code', model: 'claude-fable-5', sessionHint: null, unstable: false },
    task: { goal: 'Scan every rendered output', constraints: ['Deterministic output'], acceptance: [] },
    plan: { steps: [{ id: 's1', title: 'Render', status: 'active', note: null }] },
    decisions: [{ seq: 1, ts: T0, summary: 'no attribution anywhere' }],
    files: { touched: [{ path: 'README.md', op: 'edit', lastTs: T0 }] },
    roles: { assignments: {} },
    git: null,
    handoff: { status: 'open', reason: null, reasonClass: null, toPlatformHint: null, finalizedAt: null, receive_log: [] },
    journalSeq: 1,
    compaction: { droppedDecisions: 0, note: null },
    dedupeRing: [],
  };
}

function liveResumeInputs() {
  return {
    bundle: liveBundle(),
    assignments: { implementer: { platform: 'codex', model: 'gpt-5.6-sol', mode: 'native' } },
    warnings: [],
    origin: 'claude-code',
    reason: "You've hit your usage limit",
  };
}

// ===========================================================================
describe('attribution invariant — shipped templates/ tree (A1)', () => {
  it('templates/ exists, carries the three pinned template files, and NO file under it holds an AI-credit string', () => {
    assert.ok(existsSync(TEMPLATES_DIR), 'the shipped templates/ directory must exist (plan repo map; the templates commit precedes scaffold/init)');

    const files = walkFiles(TEMPLATES_DIR);
    assert.ok(files.length > 0, 'templates/ must not be empty — an empty tree would make this arm vacuous');

    const names = files.map((f) => relative(TEMPLATES_DIR, f));
    for (const required of ['AGENTS.md.tpl', 'CLAUDE.md.tpl', 'baton.config.json.tpl']) {
      assert.ok(names.includes(required), `the pinned template ${required} must ship in templates/`);
    }

    for (const f of files) {
      assert.deepEqual(scanAttribution(readFileSync(f, 'utf8')), [], `template ${relative(repoRoot, f)} must carry no attribution string`);
    }
  });
});

// ===========================================================================
describe('attribution invariant — committed golden fixtures (A2, discovered dynamically)', () => {
  it('every file under tests/helpers/fixtures/golden/ is scanned and clean', () => {
    const files = walkFiles(GOLDEN_DIR);
    assert.ok(files.length > 0, 'the golden fixtures directory must yield files to scan (non-vacuous)');
    for (const f of files) {
      assert.deepEqual(scanAttribution(readFileSync(f, 'utf8')), [], `golden ${relative(repoRoot, f)} must carry no attribution string`);
    }
  });
});

// ===========================================================================
describe('attribution invariant — live rendered output (A3)', () => {
  it('renderHandoffMd + renderResumePrompt output carry no AI-credit string', () => {
    const outputs = [renderHandoffMd(liveBundle()), renderResumePrompt(liveResumeInputs())];
    for (const out of outputs) {
      assert.ok(out.length > 0, 'a live render produced output to scan (non-vacuous)');
      assert.deepEqual(scanAttribution(out), [], 'live rendered output must carry no attribution string');
    }
  });
});

// ===========================================================================
describe('attribution invariant — scaffold previews (A4, planInit)', () => {
  it('every preview baton init would write carries no AI-credit string', () => {
    const cwd = mkdtempSync(join(tmpdir(), 'baton-attr-inv-'));
    try {
      const io = {
        cwd,
        env: {},
        stdin: '',
        stdout: { write: () => true },
        stderr: { write: () => true },
        fs: nodeFs,
        execFile: () => Promise.reject(new Error('no exec in invariant scan')),
        now: () => T0,
        host: 'inv-host',
        pid: 4242,
        startTime: 111000,
        processAlive: (pid) => pid === 4242,
        newFencingToken: () => 'inv-tok',
      };
      const actions = planInit(cwd, {}, io);
      assert.ok(Array.isArray(actions) && actions.length > 0, 'planInit yields scaffold actions to scan');

      let previewsScanned = 0;
      for (const a of actions) {
        if (typeof a.preview !== 'string') continue;
        previewsScanned += 1;
        assert.deepEqual(scanAttribution(a.preview), [], `scaffold preview for ${a.path} must carry no attribution string`);
      }
      assert.ok(previewsScanned > 0, 'at least one scaffold preview was scanned (the rendered-scaffold arm is non-vacuous)');
    } finally {
      rmSync(cwd, { recursive: true, force: true });
    }
  });
});

// ===========================================================================
describe('attribution invariant — the scanner has teeth', () => {
  it('positive control: known attribution strings ARE flagged', () => {
    assert.ok(scanAttribution('Co-Authored-By: Claude <noreply@anthropic.com>').length > 0);
    assert.ok(scanAttribution('🤖 Generated with Claude Code').length > 0);
    assert.ok(scanAttribution('This was written by an AI').length > 0);
  });
});
