import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync, readdirSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join, dirname, relative } from 'node:path';

// ---------------------------------------------------------------------------
// ADAPTERS wave — RED. Static-surface contract for the Codex adapter templates.
//
// SOLE RED CAUSE: the files below do not exist yet; each block asserts the file
// exists FIRST with an unambiguous message (a clear "file missing", never
// ERR_MODULE_NOT_FOUND — no not-yet-authored module is imported here).
//
// Source of truth: plan §Codex adapter + platform-notes §Codex CLI (hooks.json
// shape lives at repo .codex/hooks.json; commandWindows override; Agent Skills
// standard at .agents/skills).
//
// PINS (open layout resolved here):
//   C0. Adapter tree layout (documented choice, mirroring the Claude adapter's
//       flat template layout):
//         adapters/codex/hooks.json                      — template for the
//                                                           repo's .codex/hooks.json
//         adapters/codex/.agents/skills/baton-handoff/SKILL.md
//   C1. hooks.json shape = the proven Codex hook manifest format (mirrors the
//       installed codex-plugin hooks): { "hooks": { "<Event>": [ { "hooks":
//       [ { "type":"command", "command": string,
//           "commandWindows": string } ] } ] } }.
//   C2. Exactly three events — Stop, PreCompact, SessionStart (no StopFailure on
//       Codex).
//   C3. Every command reaches baton. (Verifier fold V8: exact stamping) EVERY
//       Stop and EVERY PreCompact command invokes `checkpoint` carrying
//       `--platform codex`; EVERY SessionStart command is the universal-fallback
//       pending-handoff notice `receive --print-prompt --platform codex`, never
//       a `checkpoint`.
//   C4. Every command hook carries a Windows override (commandWindows /
//       command_windows) — Codex is the only harness with a Windows-specific
//       command field (platform-notes).
//   C5. .agents/skills/baton-handoff/SKILL.md carries frontmatter name +
//       description (Agent Skills standard).
//   C6. Zero-attribution scan over the whole Codex adapter surface.
// ---------------------------------------------------------------------------

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..', '..');
const ADAPTER_DIR = join(repoRoot, 'adapters', 'codex');
const HOOKS_JSON = join(ADAPTER_DIR, 'hooks.json');
const SKILL_MD = join(ADAPTER_DIR, '.agents', 'skills', 'baton-handoff', 'SKILL.md');

const miss = (p, who) => `${p} must exist — the ADAPTERS wave implementer authors ${who} here`;
const EXPECTED_EVENTS = ['Stop', 'PreCompact', 'SessionStart'];

const ATTRIBUTION_PATTERNS = [
  /co-authored-by/i,
  /generated with claude/i,
  /generated by claude/i,
  /🤖/,
  /written by (an? )?ai\b/i,
  /authored by (an? )?ai\b/i,
  /powered by claude/i,
];
const scanAttribution = (text) => ATTRIBUTION_PATTERNS.filter((re) => re.test(text)).map((re) => re.source);

/** @param {string} dir */
function walkFiles(dir) {
  /** @type {string[]} */
  const out = [];
  if (!existsSync(dir)) return out;
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...walkFiles(p));
    else out.push(p);
  }
  return out;
}

function loadHooks() {
  assert.ok(existsSync(HOOKS_JSON), miss(HOOKS_JSON, 'the Codex .codex/hooks.json template'));
  const json = JSON.parse(readFileSync(HOOKS_JSON, 'utf8'));
  assert.ok(json && typeof json.hooks === 'object' && json.hooks !== null, 'the template carries a top-level "hooks" object');
  return json.hooks;
}

function commandItems(hooks, event) {
  const groups = hooks[event];
  assert.ok(Array.isArray(groups) && groups.length > 0, `event ${event} maps to a non-empty array of hook groups`);
  const items = [];
  for (const g of groups) {
    assert.ok(g && Array.isArray(g.hooks), `each ${event} group carries a hooks[] array`);
    items.push(...g.hooks);
  }
  return items;
}
const hasWinOverride = (item) => typeof item.commandWindows === 'string' || typeof item.command_windows === 'string';

// ===========================================================================
describe('codex hooks.json template — event coverage (C2)', () => {
  it('configures EXACTLY Stop, PreCompact, SessionStart (no StopFailure on Codex)', () => {
    const hooks = loadHooks();
    assert.deepEqual([...Object.keys(hooks)].sort(), [...EXPECTED_EVENTS].sort());
  });
});

// ===========================================================================
describe('codex hooks.json template — command wiring reaches baton (C1, C3)', () => {
  it('EVERY Stop + PreCompact command is checkpoint --platform codex; EVERY SessionStart command is receive --print-prompt --platform codex', () => {
    const hooks = loadHooks();
    for (const event of EXPECTED_EVENTS) {
      for (const item of commandItems(hooks, event)) {
        assert.equal(item.type, 'command', `${event} hooks are command hooks`);
        assert.ok(String(item.command).includes('baton'), `${event} command invokes baton`);
      }
    }
    // (iter-2) The Windows override is a full peer of `command`: every
    // per-event expectation is asserted on BOTH strings, so a Windows machine
    // gets the same subcommand/platform/fallback wiring.
    const bothCommands = (/** @type {any} */ i) => [i.command, i.commandWindows ?? i.command_windows].filter((c) => typeof c === 'string');
    for (const event of ['Stop', 'PreCompact']) {
      for (const i of commandItems(hooks, event)) {
        for (const cmd of bothCommands(i)) {
          assert.match(String(cmd), /checkpoint/, `${event} -> checkpoint (command and Windows override)`);
          assert.match(String(cmd), /--platform codex\b/, `(V8/iter-2) the ${event} checkpoint carries --platform codex on both command strings`);
        }
      }
    }
    for (const i of commandItems(hooks, 'SessionStart')) {
      for (const cmd of bothCommands(i).map(String)) {
        assert.doesNotMatch(cmd, /checkpoint/, 'SessionStart is a pending-handoff notice, not a checkpoint (both command strings)');
        assert.match(cmd, /receive/, '(V8) the SessionStart notice runs baton receive');
        assert.match(cmd, /--print-prompt\b/, '(V8) the notice uses the universal --print-prompt fallback (prepare-only, no mutation)');
        assert.match(cmd, /--platform codex\b/, '(V8/iter-2) the notice carries --platform codex on both command strings');
      }
    }
  });
});

// ===========================================================================
describe('codex hooks.json template — Windows overrides present (C4)', () => {
  it('every command hook carries a commandWindows override', () => {
    const hooks = loadHooks();
    for (const event of EXPECTED_EVENTS) {
      for (const item of commandItems(hooks, event)) {
        assert.ok(hasWinOverride(item), `${event} command carries a commandWindows override`);
      }
    }
  });
});

// ===========================================================================
describe('codex baton-handoff skill (C5)', () => {
  it('.agents/skills/baton-handoff/SKILL.md exists with a name + description', () => {
    assert.ok(existsSync(SKILL_MD), miss(SKILL_MD, 'the Codex baton-handoff skill'));
    const md = readFileSync(SKILL_MD, 'utf8');
    const m = md.match(/^---\n([\s\S]*?)\n---/);
    assert.ok(m, 'SKILL.md has YAML frontmatter');
    assert.match(m[1], /(^|\n)name:\s*baton-handoff\b/, 'SKILL.md declares name: baton-handoff');
    assert.match(m[1], /(^|\n)description:\s*\S/, 'SKILL.md declares a description');
  });
});

// ===========================================================================
describe('codex adapter — zero-attribution scan (C6)', () => {
  it('no file under adapters/codex/** carries an AI-credit string', () => {
    assert.ok(existsSync(ADAPTER_DIR), miss(ADAPTER_DIR, 'the Codex adapter surface'));
    const files = walkFiles(ADAPTER_DIR);
    assert.ok(files.length > 0, 'the Codex adapter surface must yield files to scan (non-vacuous)');
    for (const f of files) {
      assert.deepEqual(scanAttribution(readFileSync(f, 'utf8')), [], `${relative(repoRoot, f)} must carry no attribution string`);
    }
  });
});
