import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync, readdirSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join, dirname, relative } from 'node:path';

// ---------------------------------------------------------------------------
// ADAPTERS wave — RED. Static-surface contract for the Cursor adapter templates.
//
// SOLE RED CAUSE: the files below do not exist yet; each block asserts the file
// exists FIRST with an unambiguous message (a clear "file missing", never
// ERR_MODULE_NOT_FOUND — no not-yet-authored module is imported).
//
// Source of truth: plan §Cursor adapter + platform-notes §Cursor (VERIFIED hook
// events + the {"version":1,"hooks":{...}} shape; no commandWindows — cross-
// platform command strings; beforeShellExecution git-commit matcher; SCM-UI
// commits are invisible, documented limitation).
//
// PINS (open layout resolved here, mirroring the flat adapter template layout):
//   U0. Adapter tree:
//         adapters/cursor/hooks.json                 — template for .cursor/hooks.json
//         adapters/cursor/commands/{receive,handoff,baton-setup}.md
//         adapters/cursor/rules/baton-handoff.mdc
//   U1. hooks.json shape = the verified Cursor format:
//         {"version":1,"hooks":{"<event>":[{"command":string,
//                                            "timeout"?:number,"matcher"?:string}]}}
//       (leaf items are flat {command,…}, NOT the nested {hooks:[…]} Claude form).
//   U2. version === 1.
//   U3. Exactly the FIVE verified events — stop, afterFileEdit,
//       beforeShellExecution, sessionStart, preCompact — and NO others.
//   U4. Every command invokes baton. (Verifier fold V9: exact stamping) EVERY
//       item of stop / afterFileEdit / beforeShellExecution / preCompact invokes
//       `checkpoint` carrying `--platform cursor`; EVERY sessionStart item is
//       the cheap pending-foreign gate `session-start --platform cursor`
//       (gate-2 fix 8 — never full receive preparation, never a `checkpoint`).
//   U5. beforeShellExecution carries a matcher that SPECIFICALLY identifies git
//       commits — 'git' preceding 'commit' (e.g. 'git commit' or a git-anchored
//       pattern), not any command containing 'commit' (verifier fold V10).
//   U6. NO commandWindows / command_windows anywhere (Cursor uses cross-platform
//       command strings).
//   U7. commands/*.md carry a description in frontmatter.
//   U8. rules/baton-handoff.mdc frontmatter sets alwaysApply: true and its body
//       is <=5 non-empty lines.
//   U9. Zero-attribution scan over the whole Cursor adapter surface.
// ---------------------------------------------------------------------------

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..', '..');
const ADAPTER_DIR = join(repoRoot, 'adapters', 'cursor');
const HOOKS_JSON = join(ADAPTER_DIR, 'hooks.json');
const COMMANDS_DIR = join(ADAPTER_DIR, 'commands');
const RULE_MDC = join(ADAPTER_DIR, 'rules', 'baton-handoff.mdc');

const miss = (p, who) => `${p} must exist — the ADAPTERS wave implementer authors ${who} here`;
const EXPECTED_EVENTS = ['stop', 'afterFileEdit', 'beforeShellExecution', 'sessionStart', 'preCompact'];
const CHECKPOINT_EVENTS = ['stop', 'afterFileEdit', 'beforeShellExecution', 'preCompact'];

const ATTRIBUTION_PATTERNS = [
  /co-authored-by/i,
  /generated with claude/i,
  /generated by claude/i,
  /🤖/,
  /written by (an? )?ai\b/i,
  /authored by (an? )?ai\b/i,
  /powered by claude/i,
];
const scanAttribution = (text) => ATTRIBUTION_PATTERNS.filter((re) => re.test(text)).map((re) => re.source);

/** @param {string} dir */
function walkFiles(dir) {
  /** @type {string[]} */
  const out = [];
  if (!existsSync(dir)) return out;
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...walkFiles(p));
    else out.push(p);
  }
  return out;
}
function frontmatter(md) {
  const m = md.match(/^---\n([\s\S]*?)\n---/);
  return m ? m[1] : null;
}

function loadCfg() {
  assert.ok(existsSync(HOOKS_JSON), miss(HOOKS_JSON, 'the Cursor .cursor/hooks.json template'));
  const json = JSON.parse(readFileSync(HOOKS_JSON, 'utf8'));
  assert.ok(json && typeof json.hooks === 'object' && json.hooks !== null, 'the template carries a top-level "hooks" object');
  return json;
}
function items(hooks, event) {
  const arr = hooks[event];
  assert.ok(Array.isArray(arr) && arr.length > 0, `event ${event} maps to a non-empty array of hook items`);
  return arr;
}

// ===========================================================================
describe('cursor hooks.json template — version + event coverage (U2, U3)', () => {
  it('is version 1 and configures EXACTLY the five verified events', () => {
    const cfg = loadCfg();
    assert.equal(cfg.version, 1, 'the Cursor hooks manifest is {"version":1,…}');
    assert.deepEqual([...Object.keys(cfg.hooks)].sort(), [...EXPECTED_EVENTS].sort(), 'only the verified events are used');
  });
});

// ===========================================================================
describe('cursor hooks.json template — command wiring (U1, U4)', () => {
  it('every item is a flat {command} invoking baton; EVERY checkpoint item carries --platform cursor; sessionStart is session-start --platform cursor', () => {
    const { hooks } = loadCfg();
    for (const event of EXPECTED_EVENTS) {
      for (const item of items(hooks, event)) {
        assert.ok(typeof item.command === 'string' && item.command.length > 0, `${event} item is a flat {command} string`);
        assert.ok(item.command.includes('baton'), `${event} command invokes baton`);
      }
    }
    for (const event of CHECKPOINT_EVENTS) {
      for (const i of items(hooks, event)) {
        assert.match(String(i.command), /checkpoint/, `${event} -> checkpoint`);
        assert.match(String(i.command), /--platform cursor\b/, `(V9) the ${event} checkpoint carries --platform cursor`);
      }
    }
    for (const i of items(hooks, 'sessionStart')) {
      const cmd = String(i.command);
      assert.doesNotMatch(cmd, /checkpoint/, 'sessionStart is a pending-handoff notice, not a checkpoint');
      // (gate-2 fix 8) sessionStart must NOT run full receive preparation —
      // exit-1 noise with no bundle, prompts for own open bundles, and the
      // wrong output shape for Cursor. `baton session-start` emits the Cursor
      // additional_context JSON and always exits 0.
      assert.doesNotMatch(cmd, /receive/, '(gate-2 fix 8) sessionStart never runs receive preparation');
      assert.match(cmd, /session-start\b/, '(gate-2 fix 8) the notice is the cheap session-start gate (pending-foreign only, always exit 0)');
      assert.match(cmd, /--platform cursor\b/, '(V9) the notice carries --platform cursor');
    }
  });
});

// ===========================================================================
describe('cursor hooks.json template — git-commit matcher + no Windows override (U5, U6)', () => {
  it('beforeShellExecution carries a matcher that SPECIFICALLY identifies git commits (git-anchored, not bare "commit")', () => {
    const { hooks } = loadCfg();
    const matchers = items(hooks, 'beforeShellExecution').map((i) => String(i.matcher ?? ''));
    // (V10) 'git' must precede 'commit' in the matcher — a bare /commit/ matcher
    // (which would also fire on e.g. `svn commit` or `commitlint`) fails this.
    // (iter-2) EVERY item must carry a git-anchored matcher: `some` would let a
    // valid matcher coexist with an unfiltered sibling that still fires on
    // non-git commits.
    assert.ok(matchers.length > 0, 'beforeShellExecution carries at least one hook item');
    for (const m of matchers) {
      assert.match(
        m,
        /git[^]*commit/i,
        `every beforeShellExecution checkpoint item needs a git-anchored commit matcher (e.g. "git commit"); got: ${JSON.stringify(matchers)}`,
      );
    }
  });

  it('no commandWindows / command_windows appears anywhere (cross-platform strings)', () => {
    assert.ok(existsSync(HOOKS_JSON), miss(HOOKS_JSON, 'the Cursor .cursor/hooks.json template'));
    const raw = readFileSync(HOOKS_JSON, 'utf8');
    assert.doesNotMatch(raw, /command_?[wW]indows/, 'Cursor uses cross-platform command strings — no Windows override field');
  });
});

// ===========================================================================
describe('cursor commands (U7)', () => {
  for (const name of ['receive', 'handoff', 'baton-setup']) {
    it(`${name}.md exists with a description in frontmatter`, () => {
      const p = join(COMMANDS_DIR, `${name}.md`);
      assert.ok(existsSync(p), miss(p, `the Cursor ${name} command`));
      const fm = frontmatter(readFileSync(p, 'utf8'));
      assert.ok(fm, `${name}.md has a YAML frontmatter block`);
      assert.match(fm, /(^|\n)description:\s*\S/, `${name}.md frontmatter declares a description`);
    });
  }
});

// ===========================================================================
describe('cursor baton-handoff rule (U8)', () => {
  it('baton-handoff.mdc sets alwaysApply: true and its body is <=5 non-empty lines', () => {
    assert.ok(existsSync(RULE_MDC), miss(RULE_MDC, 'the baton-handoff Cursor rule'));
    const md = readFileSync(RULE_MDC, 'utf8');
    const fm = frontmatter(md);
    assert.ok(fm, '.mdc has YAML frontmatter');
    assert.match(fm, /(^|\n)alwaysApply:\s*true\b/, 'the rule sets alwaysApply: true');

    const body = md.replace(/^---\n[\s\S]*?\n---/, '');
    const bodyLines = body.split('\n').map((l) => l.trim()).filter((l) => l.length > 0);
    assert.ok(bodyLines.length <= 5, `the rule body must be <=5 non-empty lines (got ${bodyLines.length})`);
  });
});

// ===========================================================================
describe('cursor adapter — zero-attribution scan (U9)', () => {
  it('no file under adapters/cursor/** carries an AI-credit string', () => {
    assert.ok(existsSync(ADAPTER_DIR), miss(ADAPTER_DIR, 'the Cursor adapter surface'));
    const files = walkFiles(ADAPTER_DIR);
    assert.ok(files.length > 0, 'the Cursor adapter surface must yield files to scan (non-vacuous)');
    for (const f of files) {
      assert.deepEqual(scanAttribution(readFileSync(f, 'utf8')), [], `${relative(repoRoot, f)} must carry no attribution string`);
    }
  });
});
